type NodeRequest = {
  method?: string;
  url?: string;
  headers: Record<string, string | string[] | undefined>;
};
type NodeReply = {
  statusCode: number;
  setHeader(name: string, value: string | string[]): void;
  end(body?: Buffer): void;
};

export default async function handler(request: NodeRequest, reply: NodeReply) {
  // Generated by `npm run build` before Vercel packages this function.
  const { default: worker } = await import('../dist/server/index.js');
  const host = request.headers.host;
  const url = new URL(request.url || '/', `https://${host}`);
  const headers = new Headers();
  for (const [name, value] of Object.entries(request.headers)) {
    if (Array.isArray(value)) value.forEach((item) => headers.append(name, item));
    else if (value !== undefined) headers.set(name, value);
  }
  const webResponse = await worker.fetch(
    new Request(url, { method: request.method || 'GET', headers }),
    {},
    { waitUntil() {}, passThroughOnException() {} },
  );
  reply.statusCode = webResponse.status;
  webResponse.headers.forEach((value: string, name: string) =>
    reply.setHeader(name, value),
  );
  reply.end(Buffer.from(await webResponse.arrayBuffer()));
}
